# -*- coding: utf-8 -*-
"""cervicalcancerdetectionmcaproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZChbhp3W9ZxQ_mGwwV705_JYgL1Ak0Sc

TO MOUNT DRIVE
"""

from google.colab import drive
drive.mount('/content/drive')

"""EXTRACTING DATASET ZIPFILE"""

import zipfile

zip_path = '/content/drive/MyDrive/Herlev_PapSmear.zip'  # Change this to your ZIP file path
extract_path = '/content/dataset'  # Where you want to extract

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, save_img

"""USING TRAIN FOLDER TO DATA AUGMEMT NEW FOLDER"""

original_train_dir = '/content/dataset/Herlev Dataset/train'                     # Original training data
augmented_dir = 'augmented_data'

os.makedirs(augmented_dir, exist_ok=True)

# Create class folders inside augmented_dir
for class_name in os.listdir(original_train_dir):
    os.makedirs(os.path.join(augmented_dir, class_name), exist_ok=True)

datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

"""DATA AUGMENTATION RATE"""

augmentations_per_image = 13

for class_name in os.listdir(original_train_dir):
    class_path = os.path.join(original_train_dir, class_name)
    output_class_path = os.path.join(augmented_dir, class_name)

    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)

        # Load and convert to NumPy array
        img = load_img(img_path)
        x = img_to_array(img)
        x = x.reshape((1,) + x.shape)  # shape: (1, height, width, channels)

        # Save original image to output
        save_img(os.path.join(output_class_path, img_name), x[0])

        # Generate and save 13 augmented images
        i = 0
        for batch in datagen.flow(x, batch_size=1):
            aug_img_name = f"{os.path.splitext(img_name)[0]}_aug{i+1}.png"
            save_path = os.path.join(output_class_path, aug_img_name)
            save_img(save_path, batch[0])
            i += 1
            if i >= augmentations_per_image:
                break

"""BALANCING THE CLASSES WITH SAME NUMBER OF IMAGES"""

import os
import random
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, save_img

# Directories
input_dir = '/content/augmented_data'  # Already contains some augmented images
target_per_class = 1794  # Target size for each class

# Data augmentation config
datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

# Count images in each class and augment if needed
for class_name in sorted(os.listdir(input_dir)):
    class_path = os.path.join(input_dir, class_name)
    image_files = [
        f for f in os.listdir(class_path)
        if os.path.isfile(os.path.join(class_path, f)) and f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ]

    current_count = len(image_files)
    print(f"🔸 {class_name}: {current_count} images")

    if current_count >= target_per_class:
        print(f"✅ {class_name} already has enough images. Skipping.\n")
        continue

    # How many more we need
    needed = target_per_class - current_count
    print(f"🛠️ Augmenting {needed} more images for class: {class_name}")

    # Augment randomly selected images
    i = 0
    while i < needed:
        img_name = random.choice(image_files)
        img_path = os.path.join(class_path, img_name)
        img = load_img(img_path)
        x = img_to_array(img)
        x = x.reshape((1,) + x.shape)

        for batch in datagen.flow(x, batch_size=1):
            aug_img_name = f"{os.path.splitext(img_name)[0]}_bal{i+1}.png"
            aug_img_path = os.path.join(class_path, aug_img_name)
            save_img(aug_img_path, batch[0])
            i += 1
            if i >= needed:
                break

    print(f"✅ {class_name} is now balanced with {target_per_class} images.\n")

from google.colab import files

files.download('/content/drive/MyDrive/augmented_data')

pip install split-folders

"""SPLITING THE AUGMENTED FOLDER INTO TRAIN,VAL AND TEST"""

import splitfolders

splitfolders.ratio(
    "/content/augmented_data",                # Your full dataset path
    output="/content/split_data2",             # Output path for split data
    seed=123,                                 # For reproducibility
    ratio=(0.7,0.1,0.2),                         # 70% training, 10% validation,20% testing
    move=False                                # Set to True if you want to move instead of copy
)

"""CHECKING IF THE FOLDERS ARE SPLITED IN THE CORRECT RATIO"""

import os

def count_images_in_folders(base_dir):
    sets = ['train', 'val', 'test']
    total_counts = {}

    for split in sets:
        split_path = os.path.join(base_dir, split)
        if not os.path.exists(split_path):
            print(f"❌ Folder '{split}' not found in {base_dir}")
            continue

        print(f"\n📂 Counting in '{split}' folder:")
        split_total = 0
        for class_name in os.listdir(split_path):
            class_dir = os.path.join(split_path, class_name)
            if not os.path.isdir(class_dir):
                continue

            count = len([
                f for f in os.listdir(class_dir)
                if f.lower().endswith(('.jpg', '.jpeg', '.png'))
            ])
            print(f"  - {class_name}: {count} images")
            split_total += count

        total_counts[split] = split_total
        print(f"🔢 Total in '{split}': {split_total} images")

    print("\n📊 Overall Summary:")
    for split in sets:
        print(f"  {split}: {total_counts.get(split, 0)} images")

# Example usage
count_images_in_folders(base_dir="/content/split_data2")  # Replace with your dataset root folder

"""EFFICIENTNETB0 MODEL

"""

# Install TensorFlow if needed
# !pip install tensorflow

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.preprocessing import image_dataset_from_directory
import matplotlib.pyplot as plt
import numpy as np
import os

# Settings
BATCH_SIZE = 32
IMG_SIZE = (224, 224)
EPOCHS = 50

train_ds = image_dataset_from_directory(
    "/content/split_data2/train",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_ds = image_dataset_from_directory(
    "/content/split_data2/val",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# Load test dataset
test_ds = image_dataset_from_directory(
    "/content/split_data2/test",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f"Classes: {class_names}")

# Data augmentation
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1),
])

# Prefetch
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.prefetch(buffer_size=AUTOTUNE)

# Build Model
base_model = keras.applications.EfficientNetB0(include_top=False, input_shape=IMG_SIZE + (3,), weights='imagenet')
base_model.trainable = False  # Freeze

inputs = keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = keras.applications.efficientnet.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(512, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(num_classes, activation='softmax')(x)
model = keras.Model(inputs, outputs)

# Compile
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Callbacks
early_stop = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
reduce_lr = keras.callbacks.ReduceLROnPlateau(factor=0.2, patience=5)
checkpoint = keras.callbacks.ModelCheckpoint('best_model.keras', save_best_only=True)

# Train initial model
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

# Fine-tune
base_model.trainable = True
# Freeze first 75% of layers
fine_tune_at = int(len(base_model.layers) * 0.75)
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

fine_tune_epochs = 20
total_epochs = EPOCHS + fine_tune_epochs

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=total_epochs,
    initial_epoch=history.epoch[-1],
    callbacks=[early_stop, reduce_lr, checkpoint]
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"\n📊 Test Accuracy: {test_acc*100:.2f}%")

# Save final model
model.save('final_cervical_cancer_model.keras')

# Plotting Training Curves
def plot_history(histories):
    acc = []
    val_acc = []
    loss = []
    val_loss = []

    for h in histories:
        acc += h.history['accuracy']
        val_acc += h.history['val_accuracy']
        loss += h.history['loss']
        val_loss += h.history['val_loss']

    plt.figure(figsize=(8, 8))
    plt.subplot(2, 1, 1)
    plt.plot(acc, label='Training Accuracy')
    plt.plot(val_acc, label='Validation Accuracy')
    plt.legend()
    plt.subplot(2, 1, 2)
    plt.plot(loss, label='Training Loss')
    plt.plot(val_loss, label='Validation Loss')
    plt.legend()
    plt.xlabel('Epochs')
    plt.show()

plot_history([history, history_fine])

"""CLASSIFICATION REPORT AND CONFUSION MATRIX FOR EFFICIENTNETB0 MODEL"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import numpy as np

# Get predictions and true labels
y_pred = np.argmax(model.predict(test_ds), axis=1)
y_true = np.concatenate([y.numpy() for x, y in test_ds], axis=0)

# Classification Report
print("\n📝 Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names, cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""CNN MODEL WITH CLASSIFICATION REPORT,CONFUSION MATRIX,VALIDATION AND TEST ACCURACY"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, callbacks
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import cv2

# Paths
train_path = '/content/split_data2/train'
val_path = '/content/split_data2/val'
test_path = '/content/split_data2/test'


# Image and batch size
IMAGE_SIZE = 224
BATCH_SIZE = 32

# Data generators
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

val_generator = val_datagen.flow_from_directory(
    val_path,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test_path,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)


NUM_CLASSES = train_generator.num_classes
class_labels = list(val_generator.class_indices.keys())

# Improved CNN Model
model = models.Sequential([
    layers.Conv2D(64, (3, 3), activation='relu', padding='same', input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3)),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(256, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='last_conv'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),

    layers.Dense(NUM_CLASSES, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# Callbacks
early_stop = callbacks.EarlyStopping(patience=8, restore_best_weights=True)
checkpoint = callbacks.ModelCheckpoint('best_cnn_model.h5', save_best_only=True)
lr_schedule = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4)

# Training
history = model.fit(
    train_generator,
    epochs=50,
    validation_data=val_generator,
    callbacks=[early_stop, checkpoint, lr_schedule]
)

# Evaluation
val_loss, val_acc = model.evaluate(val_generator)
print(f"\nValidation Accuracy: {val_acc * 100:.2f}%")

# Predictions
y_pred = model.predict(val_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = val_generator.classes

# Classification Report
print("\nClassification Report:")
print(classification_report(y_true, y_pred_classes, target_names=class_labels))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()# Evaluate on Test Set
test_loss, test_acc = model.evaluate(test_generator)
print(f"\n📊 Test Accuracy: {test_acc * 100:.2f}%")

# Test Set Predictions
y_test_pred = model.predict(test_generator)
y_test_pred_classes = np.argmax(y_test_pred, axis=1)
y_test_true = test_generator.classes

# Classification Report for Test Set
print("\n📝 Test Set Classification Report:")
print(classification_report(y_test_true, y_test_pred_classes, target_names=class_labels))

# Confusion Matrix for Test Set
cm_test = confusion_matrix(y_test_true, y_test_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Greens', xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Test Set Confusion Matrix")
plt.show()

"""VISION TRANSFORMERS MODEL"""

# ✅ STEP 1: INSTALL DEPENDENCIES
!pip install -q transformers timm torchvision

# ✅ STEP 2: IMPORTS
import os
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torchvision.transforms import Compose, Resize, ToTensor, Normalize
from torch.utils.data import DataLoader
from transformers import ViTFeatureExtractor, ViTForImageClassification
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# ✅ STEP 3: SET DEVICE
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ✅ STEP 4: LOAD FEATURE EXTRACTOR
feature_extractor = ViTFeatureExtractor.from_pretrained('google/vit-base-patch16-224-in21k')
image_size = feature_extractor.size['height']

# ✅ STEP 5: DATA TRANSFORMS
transform = Compose([
    Resize((image_size, image_size)),
    ToTensor(),
    Normalize(mean=feature_extractor.image_mean, std=feature_extractor.image_std)
])

# ✅ STEP 6: DATASET PATHS
train_path = "/content/split_data2/train"
val_path = "/content/split_data2/val"
test_path = "/content/split_data2/test"


# ✅ STEP 7: LOAD DATA
train_dataset = datasets.ImageFolder(train_path, transform=transform)
val_dataset = datasets.ImageFolder(val_path, transform=transform)
test_dataset = datasets.ImageFolder(test_path, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)
test_loader = DataLoader(test_dataset, batch_size=16)


num_classes = len(train_dataset.classes)
class_names = train_dataset.classes

# ✅ STEP 8: LOAD MODEL
model = ViTForImageClassification.from_pretrained(
    'google/vit-base-patch16-224-in21k',
    num_labels=num_classes
)
model.to(device)

# ✅ STEP 9: TRAINING SETUP
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

# ✅ STEP 10: TRAINING LOOP
def train_model(model, train_loader, val_loader, epochs=5):
    for epoch in range(epochs):
        model.train()
        total_loss, correct, total = 0, 0, 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(pixel_values=images).logits
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            preds = torch.argmax(outputs, dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        acc = correct / total
        print(f"Epoch {epoch+1}: Train Loss = {total_loss:.4f}, Train Accuracy = {acc*100:.2f}%")

        # Validation
        model.eval()
        val_preds, val_labels = [], []

        with torch.no_grad():
            for images, labels in val_loader:
                images = images.to(device)
                outputs = model(pixel_values=images).logits
                preds = torch.argmax(outputs, dim=1).cpu().numpy()

                val_preds.extend(preds)
                val_labels.extend(labels.numpy())

        val_acc = accuracy_score(val_labels, val_preds)
        print(f"          Val Accuracy = {val_acc*100:.2f}%")

    return model

# ✅ STEP 11: START TRAINING
trained_model = train_model(model, train_loader, val_loader, epochs=5)

"""TEST ACCURACY AND CLASSIFICATION REPORT FOR VIT MODEL"""

def test_model(model, test_loader):
    model.eval()
    test_preds, test_labels = [], []

    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            outputs = model(pixel_values=images).logits
            preds = torch.argmax(outputs, dim=1).cpu().numpy()

            test_preds.extend(preds)
            test_labels.extend(labels.numpy())

    test_acc = accuracy_score(test_labels, test_preds)
    print(f"\n✅ Test Accuracy = {test_acc*100:.2f}%")
    print("\n📄 Classification Report on Test Set:")
    print(classification_report(test_labels, test_preds, target_names=class_names))

test_model(trained_model, test_loader)

"""GRADCAM AND SOME EXAMPLES

EXAMPLE 01
"""

# ✅ IMPORTS
import torch
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image

# ✅ GradCAM Utilities
def normalize_cam(cam):
    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-5)
    return cam

def generate_vit_gradcam(model, image_tensor, device):
    model.eval()
    image_tensor = image_tensor.unsqueeze(0).to(device)

    activations = []
    gradients = []

    def forward_hook(module, input, output):
        activations.append(output)

    def backward_hook(module, grad_in, grad_out):
        gradients.append(grad_out[0])

    # Hook into last encoder block's output
    target_layer = model.vit.encoder.layer[-1].output
    fwd_handle = target_layer.register_forward_hook(forward_hook)
    bwd_handle = target_layer.register_full_backward_hook(backward_hook)

    outputs = model(pixel_values=image_tensor).logits
    pred_class = outputs.argmax(dim=1)
    loss = outputs[:, pred_class]

    model.zero_grad()
    loss.backward()

    grads = gradients[0]     # (batch_size, seq_len, hidden_dim)
    acts = activations[0]    # (batch_size, seq_len, hidden_dim)

    weights = grads.mean(dim=-1)  # (batch_size, seq_len)
    cam = (weights.unsqueeze(-1) * acts).sum(dim=1)  # (batch_size, seq_len)

    cam = cam.squeeze(0)  # Remove batch
    cam = normalize_cam(cam.cpu().detach().numpy())

    cam = cam[1:]  # Remove CLS token

    # ✅ Now make cam square
    num_patches = cam.shape[0]  # 767
    side = int(np.ceil(np.sqrt(num_patches)))  # 28

    pad_len = (side * side) - num_patches  # 784 - 767 = 17
    cam = np.pad(cam, (0, pad_len), mode='constant')  # Pad 0s

    cam = cam.reshape(side, side)

    # ✅ Convert to torch tensor and interpolate to (224, 224)
    cam = torch.tensor(cam).unsqueeze(0).unsqueeze(0)  # (1, 1, side, side)
    cam = torch.nn.functional.interpolate(cam, size=(224, 224), mode='bilinear', align_corners=False)
    cam = cam.squeeze().numpy()

    fwd_handle.remove()
    bwd_handle.remove()

    return cam

# ✅ Visualization
def show_gradcam(img_path, model, transform, device):
    img = Image.open(img_path).convert('RGB')
    img_tensor = transform(img)

    cam = generate_vit_gradcam(model, img_tensor, device)

    # Upsample CAM to match image
    cam = cv2.resize(cam, (img.width, img.height))
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    heatmap = np.float32(heatmap) / 255
    img_np = np.array(img) / 255

    superimposed_img = heatmap + img_np
    superimposed_img = superimposed_img / np.max(superimposed_img)

    plt.figure(figsize=(8, 8))
    plt.imshow(superimposed_img)
    plt.axis('off')
    plt.title('GradCAM Visualization')
    plt.show()

# ✅ Example usage
img_path = "/content/split_data2/test/carcinoma_in_situ/149143370-149143378-001.BMP"  # your image path
show_gradcam(img_path, trained_model, transform, device)

"""EXAMPLE 02"""

# ✅ IMPORTS
import torch
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image

# ✅ GradCAM Utilities
def normalize_cam(cam):
    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-5)
    return cam

def generate_vit_gradcam(model, image_tensor, device):
    model.eval()
    image_tensor = image_tensor.unsqueeze(0).to(device)

    activations = []
    gradients = []

    def forward_hook(module, input, output):
        activations.append(output)

    def backward_hook(module, grad_in, grad_out):
        gradients.append(grad_out[0])

    # Hook into last encoder block's output
    target_layer = model.vit.encoder.layer[-1].output
    fwd_handle = target_layer.register_forward_hook(forward_hook)
    bwd_handle = target_layer.register_full_backward_hook(backward_hook)

    outputs = model(pixel_values=image_tensor).logits
    pred_class = outputs.argmax(dim=1)
    loss = outputs[:, pred_class]

    model.zero_grad()
    loss.backward()

    grads = gradients[0]     # (batch_size, seq_len, hidden_dim)
    acts = activations[0]    # (batch_size, seq_len, hidden_dim)

    weights = grads.mean(dim=-1)  # (batch_size, seq_len)
    cam = (weights.unsqueeze(-1) * acts).sum(dim=1)  # (batch_size, seq_len)

    cam = cam.squeeze(0)  # Remove batch
    cam = normalize_cam(cam.cpu().detach().numpy())

    cam = cam[1:]  # Remove CLS token

    # ✅ Now make cam square
    num_patches = cam.shape[0]  # 767
    side = int(np.ceil(np.sqrt(num_patches)))  # 28

    pad_len = (side * side) - num_patches  # 784 - 767 = 17
    cam = np.pad(cam, (0, pad_len), mode='constant')  # Pad 0s

    cam = cam.reshape(side, side)

    # ✅ Convert to torch tensor and interpolate to (224, 224)
    cam = torch.tensor(cam).unsqueeze(0).unsqueeze(0)  # (1, 1, side, side)
    cam = torch.nn.functional.interpolate(cam, size=(224, 224), mode='bilinear', align_corners=False)
    cam = cam.squeeze().numpy()

    fwd_handle.remove()
    bwd_handle.remove()

    return cam

# ✅ Visualization
def show_gradcam(img_path, model, transform, device):
    img = Image.open(img_path).convert('RGB')
    img_tensor = transform(img)

    cam = generate_vit_gradcam(model, img_tensor, device)

    # Upsample CAM to match image
    cam = cv2.resize(cam, (img.width, img.height))
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    heatmap = np.float32(heatmap) / 255
    img_np = np.array(img) / 255

    superimposed_img = heatmap + img_np
    superimposed_img = superimposed_img / np.max(superimposed_img)

    plt.figure(figsize=(8, 8))
    plt.imshow(superimposed_img)
    plt.axis('off')
    plt.title('GradCAM Visualization')
    plt.show()

# ✅ Example usage
img_path = "/content/split_data2/val/severe_dysplastic/149056321-149056343-001.BMP"  # your image path
show_gradcam(img_path, trained_model, transform, device)